name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test_rust:
    name: Build and Test Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 'auto'

      - name: Download PocketIC
        run: ./scripts/download-pocket-ic.sh

      - name: Build Cargo crates
        run: cargo build --release

      - name: Build canisters
        run: dfx build --check

      - name: Test Cargo crates
        run: POCKET_IC_BIN=$(pwd)/pocket-ic cargo test --all-features

      - name: Build Cargo docs
        run: cargo doc --no-deps

      - name: Lint Rust
        run: cargo clippy --all-targets --all-features

      - name: Check Rust formatting
        run: cargo fmt --all -- --check
