name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test_rust:
    name: Build and Test Rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: 'auto'

      - name: Install PocketIC server
        uses: dfinity/pocketic@main
        with:
          pocket-ic-server-version: '12.0.0'

      - name: Confirm successful installation
        run: ${POCKET_IC_BIN} --version

      - name: Build canisters
        run: dfx build --check

      - name: Test Cargo crates
        run: cargo test --all-features

      - name: Build Cargo docs
        run: cargo doc --no-deps

      - name: Lint Rust
        run: cargo clippy --all-targets --all-features

      - name: Check Rust formatting
        run: cargo fmt --all -- --check
